kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" .Release.Name "bagetter" | trunc 63 | trimSuffix "-" }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "20Gi"
